# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: unix-64
name: astrotog

channels:
  - conda-forge

dependencies:
  - astropy=3.0
  - jupyter=1.0.0
  - matplotlib=2.1.2
  - numpy>=1.14
  - pandas=0.23.0
  - scipy=1.0.0
  - seaborn=0.9.0

  - pip:
    - sncosmo=1.5.3
    - sfdmap>=0.1.1
    - mpi4py=3.0.0
    - git+https://github.com/rbiswas4/OpSimSummary.git@master
    - git+https://github.com/rbiswas4/Cadence.git@master
