#!/bin/bash -l
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_baseline2018a
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_colossus2664
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_colossus2665
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_colossus2667
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_kraken2026
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_kraken2035
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_kraken2036
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_mothra2045
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_pontus2002
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_pontus2489
qsub /home/csetzer/astrotog/hpc_parallel/pbs_scripts/scolnic_whitepaper/lsst_sims_pontus2502
