#!/bin/csh -f
#PBS -V
#PBS -N run_LSST_hypatia_sim_kraken2036.py
#PBS -q cores24
#PBS -l nodes=1:ppn=24
#PBS -r n
#PBS -j oe
#PBS -k oe
cd /home/csetzer/astrotog/hpc_parallel

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`

#! Create a machine file
cat $PBS_NODEFILE | uniq > scripts/machine.file.$PBS_JOBID
echo PBS_NODEFILE=

time /share/apps/anaconda/python3.6/bin/python ./LSST_hypatia_sim_kraken2036.py > ./scripts/stdout.LSST_hypatia_sim_kraken2036.py$PBS_JOBID.txt
