#!/bin/bash -l
#PBS -V
#PBS -N lsst_kilonovae
#PBS -q cores24
#PBS -l nodes=1:ppn=24,walltime=99:00:00
#PBS -r n
#PBS -j oe
#PBS -k oe /home/csetzer/LSST/astrotog_output/myjob.oe
#PBS -M christian.setzer@fysik.su.se
#PBS -m be
module purge
module load python
module load mpi/mvapich/2-2.3b
source activate astrotog
cd /home/csetzer/astrotog/hpc_parallel/pbs_scripts

echo $PBS_O_WORKDIR
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:

#!Create a machine file
cat $PBS_NODEFILE | uniq > ../jobs_files/machine.file.$PBS_JOBID
echo PBS_NODEFILE=$PBS_NODEFILE

PYTHONPATH=\$PYTHONPATH:~/.conda/envs/astrotog/bin/python

mpirun -genvlist PATH,LD_LIBRARY_PATH,LD_RUN_PATH,PYTHONPATH --machinefile $PBS_NODEFILE bash ../shell_scripts/kraken2036.sh
